lvim.plugins = {
    -- Themes
    { "savq/melange" },
    { "rebelot/kanagawa.nvim" },
    { "folke/tokyonight.nvim" },

    -- DAP
    { "rcarriga/nvim-dap-ui", requires = { "mfussenegger/nvim-dap" } },
    { "theHamsta/nvim-dap-virtual-text" },
    { "mfussenegger/nvim-dap-python" },

    -- Git
    -- { "pwntester/octo.nvim", event = "BufRead" },
    { "ruifm/gitlinker.nvim", requires = "nvim-lua/plenary.nvim" },
    { "ldelossa/gh.nvim", requires = { { "ldelossa/litee.nvim" } } },
    { "sindrets/diffview.nvim", event = "BufRead" },
    { "TimUntersberger/neogit", requires = "nvim-lua/plenary.nvim" },

    -- General
    { "AndrewRadev/splitjoin.vim" },
    { "ThePrimeagen/harpoon" },
    { "ThePrimeagen/refactoring.nvim", requires = { { "nvim-lua/plenary.nvim" }, { "nvim-treesitter/nvim-treesitter" } } },
    { "ahmedkhalf/lsp-rooter.nvim", event = "BufRead" },
    { "chentoast/marks.nvim" },
    { "danymat/neogen", requires = "nvim-treesitter/nvim-treesitter" },
    { "editorconfig/editorconfig-vim" },
    { "ethanholz/nvim-lastplace", event = "BufRead" },
    -- { "folke/persistence.nvim", event = "BufReadPre", module = "persistence" },
    { "folke/todo-comments.nvim", event = "BufRead" },
    { "folke/trouble.nvim", cmd = "TroubleToggle" },
    { "karb94/neoscroll.nvim", event = "WinScrolled" },
    { "kevinhwang91/nvim-bqf", event = { "BufRead", "BufNew" } },
    { "lukas-reineke/indent-blankline.nvim", event = "BufRead" },
    { "metakirby5/codi.vim", cmd = "Codi" },
    { "mg979/vim-visual-multi" },
    { "michaelb/sniprun", run = "bash ./install.sh" },
    { "vim-test/vim-test" },
    {
        "nvim-neotest/neotest",
        requires = {
            "nvim-lua/plenary.nvim",
            "nvim-treesitter/nvim-treesitter",
            "antoinemadec/FixCursorHold.nvim",
            "nvim-neotest/neotest-plenary",
            "nvim-neotest/neotest-python",
            "nvim-neotest/neotest-vim-test",
        }
    },
    { "nvim-telescope/telescope-ui-select.nvim" },
    { "nvim-treesitter/nvim-treesitter-textobjects" },
    { "phaazon/hop.nvim", event = "BufRead" },
    { "python-rope/ropevim" },
    { "ray-x/navigator.lua", requires = { { "ray-x/guihua.lua", run = "cd lua/fzy && make" }, { "neovim/nvim-lspconfig" } } },
    { "rmagatti/auto-session" },
    { "sickill/vim-pasta" },
    { "stevearc/aerial.nvim" },
    { "tpope/vim-abolish" },
    { "tpope/vim-commentary" },
    { "tpope/vim-dispatch" },
    { "tpope/vim-eunuch" },
    { "tpope/vim-repeat" },
    { "tpope/vim-surround", keys = { "c", "d", "y" } },
    { "tpope/vim-unimpaired" },
    { "wellle/targets.vim" },
}
